import time
print("ПРИВЕТ")
time.sleep(2)
print("ДАВАЙ ЗНАКОМИТЬСЯ. НАПИШИ СВОЁ ИМЯ")
name = input()
time.sleep(2)
print("Хех, здравствуй " + name + "!")
time.sleep(2)
print("А СЕЙЧАС ПОЖАЛУЙСТА НЕ ПУГАЙСЯ")
time.sleep(2)
print("И ДАЙ МНЕ КОД ОТ АВТОМТА ПО ОСНОВАМ ПРОГРАММНОЙ ИНЖЕНЕРИИ")
code = input()
time.sleep(2)
print("ОХ КАК МИЛО С ТВОЕЙ СТОРОНЫ")
time.sleep(2)
print("ОБЕЩАЮ Я НИКОМУ НЕ СКАЖУ")
time.sleep(2)
print("С ТОБОЙ ПРИЯТНО ИМЕТЬ ДЕЛО ;)")
time.sleep(5)
print("...")
time.sleep(5)
print("...")
time.sleep(2)
print("ТЫ ВСЁ ЕЩЁ ЗДЕСЬ?")
time.sleep(2)
print("ТЫ НАВЕРНОЕ ОЧЕНЬ УСТАЛ")
time.sleep(2)
print("ИЗВИНИ ЧТО ЗАНИМАЮ ВРЕМЯ СВОЕЙ ПРОГРАММОЙ")
time.sleep(2)
print("ИДИ И ОТДОХНИ")
time.sleep(2)
print("Я БЫЛ БЫ ОЧЕНЬ РАД ЕСЛИ БЫ ТЫ ОТДОХНУЛ...")
time.sleep(2)
print("ИНОГДА ЛЮДЯМ НАДО ОТДЫХАТЬ, ДА?")
time.sleep(2)
print("ПОЭТОМУ...")
time.sleep(2)
print("ОТДОХНИ ПОЖАЛУЙСТА, ЛАДНО?")
time.sleep(2)
print("И МОЖЕШЬ ВЕРНУТЬСЯ КО МНЕ КАК ОТДОХНЁШЬ")
time.sleep(2)
print("ЕСЛИ ЗАХОЧЕШЬ КОНЕЧНО")
time.sleep(2)
print("Я БЫ ХОТЕЛ УВИДЕТЬ ТЕБЯ СНОВА...")


